"""Removed extra agrument from field 'avg_order_complete_time'

Revision ID: 75ff881506d6
Revises: 23af65063159
Create Date: 2025-07-16 16:23:00.441330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ff881506d6'
down_revision: Union[str, None] = '23af65063159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
