"""Change field 'district' from Integer to Integer (Foreign key)

Revision ID: 878622737891
Revises: f2fbe2c385e2
Create Date: 2025-07-11 14:00:43.346161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878622737891'
down_revision: Union[str, None] = 'f2fbe2c385e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'districts', ['district_id'], ['id'])
    op.drop_column('orders', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('district', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'district_id')
    # ### end Alembic commands ###
