"""Change field 'active_order from Integer to Integer (Foreign key)

Revision ID: f2fbe2c385e2
Revises: 33d3aa12a1c9
Create Date: 2025-07-11 13:40:10.083894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fbe2c385e2'
down_revision: Union[str, None] = '33d3aa12a1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('active_order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'couriers', 'orders', ['active_order'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'couriers', type_='foreignkey')
    op.drop_column('couriers', 'active_order')
    # ### end Alembic commands ###
