version: '3.9'

services:
  app:
    container_name: fastapi_app
    build:
      context: .
    ports:
      - "9999:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env-non-dev

  db:
    container_name: postgres_app
    image: postgres:latest
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-non-dev