"""Reinitial tables

Revision ID: 1501d0f0a327
Revises: 8dd0b255a22f
Create Date: 2024-04-23 19:01:23.298753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1501d0f0a327'
down_revision: Union[str, None] = '8dd0b255a22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courier', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('courier', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courier', 'order_status', ['order_id'], ['id'])
    op.create_foreign_key(None, 'courier', 'district', ['district_id'], ['id'])
    op.drop_column('courier', 'districts')
    op.add_column('order', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'order_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'order', 'district', ['district_id'], ['id'])
    op.drop_column('order', 'districts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('districts', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'status_id')
    op.drop_column('order', 'district_id')
    op.add_column('courier', sa.Column('districts', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courier', type_='foreignkey')
    op.drop_constraint(None, 'courier', type_='foreignkey')
    op.drop_column('courier', 'order_id')
    op.drop_column('courier', 'district_id')
    op.drop_table('order_status')
    op.drop_table('district')
    # ### end Alembic commands ###
