"""Changes column

Revision ID: ca7bd1bad496
Revises: bd176a63fc52
Create Date: 2024-04-23 18:43:35.736415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7bd1bad496'
down_revision: Union[str, None] = 'bd176a63fc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('districts', sa.String(length=100), nullable=False))
    op.drop_column('order', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('order', 'districts')
    # ### end Alembic commands ###
