"""Reinitial tables

Revision ID: cb1f68c12387
Revises: 1501d0f0a327
Create Date: 2024-04-23 19:39:05.927748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1f68c12387'
down_revision: Union[str, None] = '1501d0f0a327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('district', sa.Integer(), nullable=True))
    op.add_column('courier', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_constraint('courier_order_id_fkey', 'courier', type_='foreignkey')
    op.drop_constraint('courier_district_id_fkey', 'courier', type_='foreignkey')
    op.create_foreign_key(None, 'courier', 'district', ['district'], ['id'])
    op.create_foreign_key(None, 'courier', 'order_status', ['order'], ['id'])
    op.drop_column('courier', 'district_id')
    op.drop_column('courier', 'order_id')
    op.add_column('order', sa.Column('courier', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('district', sa.Integer(), nullable=True))
    op.drop_constraint('order_status_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_courier_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_district_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'district', ['district'], ['id'])
    op.create_foreign_key(None, 'order', 'order_status', ['status'], ['id'])
    op.create_foreign_key(None, 'order', 'courier', ['courier'], ['id'])
    op.drop_column('order', 'courier_id')
    op.drop_column('order', 'status_id')
    op.drop_column('order', 'district_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_district_id_fkey', 'order', 'district', ['district_id'], ['id'])
    op.create_foreign_key('order_courier_id_fkey', 'order', 'courier', ['courier_id'], ['id'])
    op.create_foreign_key('order_status_id_fkey', 'order', 'order_status', ['status_id'], ['id'])
    op.drop_column('order', 'district')
    op.drop_column('order', 'courier')
    op.add_column('courier', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('courier', sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courier', type_='foreignkey')
    op.drop_constraint(None, 'courier', type_='foreignkey')
    op.create_foreign_key('courier_district_id_fkey', 'courier', 'district', ['district_id'], ['id'])
    op.create_foreign_key('courier_order_id_fkey', 'courier', 'order_status', ['order_id'], ['id'])
    op.drop_column('courier', 'order')
    op.drop_column('courier', 'district')
    # ### end Alembic commands ###
