"""Changes column

Revision ID: eef2b7c2f431
Revises: ca7bd1bad496
Create Date: 2024-04-23 18:44:16.778504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef2b7c2f431'
down_revision: Union[str, None] = 'ca7bd1bad496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('districts', sa.String(length=100), nullable=True))
    op.drop_column('courier', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('courier', 'districts')
    # ### end Alembic commands ###
